  name: VoiceChatAutoJoin
  main: fun.kaituo.voicechatautojoin.VoiceChatAutoJoin
  version: 1.1
  api-version: 1.13
  author: YFshadaow
  depend:
    - voicechat
  commands:
      switchchat:
          description: switch between default chat and spectator chat
          aliases: [s]